<?php

namespace AppBundle\Controller;

use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Response;

class PluginsController extends Controller
{
    /**
     * @Route("/plugins", name="list_plugins")
     * @Method("GET")
     */
    public function listPlugins()
    {
        $plugins = [
            'add-attribution-feedwordpress',
            'akismet',
            'alphabetical-list',
            'appointments',
            'astickypostorderer',
            'audio-player',
            'authors',
            'auto-post-thumbnail',
            'auto-refresh-single-page',
            'badgeos',
            'bbpress',
            'blogger-importer',
            'blog-id-in-site-admin-menu',
            'careerspots-embedder',
            'category-sticky-posts',
            'chat',
            'co-authors-plus',
            'collinwood-javascript',
            'commentpress-core',
            'creative-commons-configurator-1',
            'csv-importer',
            'custom-image-sizes',
            'custom-posts-per-page',
            'custom-search-form',
            'delicious-for-wordpress',
            'digg-widget',
            'dipity-embedder',
            'disable-pingbacks',
            'display-widgets',
            'disqus-comment-system',
            'dropdown-menu-widget',
            'duplicate-post',
            'easy-faq-with-expanding-text',
            'edit-category-slug',
            'editorial-calendar',
            'email-users',
            'emma-emarketing-plugin',
            'enable-media-replace',
            'enhanced-tooltipglossary',
            'exclude-pages',
            'facebook',
            'facebook-like-box',
            'fb-status-updater',
            'featured-video-plus',
            'feedburner-email-widget',
            'feedburner_feedsmith_plugin_2.3',
            'feedwordpress',
            'feedwordpress-cdm-middhist',
            'feedwordpress-middlab',
            'flickr-rss',
            'flickr-widget',
            'ft-calendar',
            'genesis-subtitles',
            'geopress',
            'go-green-tips',
            'google-calendar-shortcode',
            'google-calendar-widget',
            'google-docs-shortcode',
            'guerrillas-recent-posts-widget',
            'hello.php',
            'im-online',
            'incsub-google-analytics.php',
            'index.php',
            'InlinePosts',
            'interactive-world-maps',
            'ix-show-latest-youtube',
            'jetpack',
            'jetpack-feedback-exporter',
            'kanopy-shortcode',
            'like',
            'lineate',
            'link-manager',
            'listmanager-subscribe',
            'liveblog',
            'mce-table-buttons',
            'members',
            'meograph-embedder',
            'middcomments',
            'middgtm.php',
            'middimages',
            'middlebury-digitalattackmap',
            'middlebury-digitalglobeimage',
            'middlebury-flashcards',
            'middlebury-mailchimp',
            'middlebury-photo-of-the-week',
            'middlebury-pinterest',
            'middlebury-preformatted',
            'middlebury-timelinejs',
            'middlebury-trailhub',
            'midd-limit-blog-registration',
            'middmedia',
            'middtube-video-plugin',
            'mingle-forum',
            'more-fields',
            'movabletype-importer',
            'multisite-plugin-manager',
            'nextgen-gallery',
            'next-page',
            'no-right-click-images-plugin',
            'notifly',
            'oai-pmh-harvester',
            'onswipe',
            'order-categories',
            'osm',
            'page-list',
            'piktochart-shortcode',
            'podcasting',
            'postcasa',
            'post-expirator',
            'post-tags-and-categories-for-pages',
            'post-types-order',
            'prezi-embedder',
            'prezi-shortcode',
            'preziwp',
            'prinz_shortcode_collection',
            'prinz_widgets',
            'private-feed-keys',
            'proper-pagination',
            'qtranslate',
            'qtranslate-x',
            'random-featured-post-plugin',
            'random-posts-from-category',
            'recent-posts-widget-extended',
            'redirection',
            'regenerate-thumbnails',
            'resize-image-after-upload',
            'restricted-site-access',
            'reverse-widget-rss',
            'rss-includes-pages',
            'schedule-posts-calendar',
            'search-everything',
            'share-this',
            'shortcodes-in-text-widgets',
            'sign-up-sheets',
            'simple-facebook-connect',
            'simple-footnotes',
            'simple-instagram',
            'simpler-ipaper',
            'simplybook',
            'sitepress-multilingual-cms',
            'social-graph-protocol',
            'social-media-badge-widget',
            'spotify-embed',
            'sticky-front-page-categories-and-tags',
            'storify',
            'subscribe2',
            'swfincluder',
            'table-of-contents-plus',
            'tell-a-friend',
            'term-management-tools',
            'the-events-calendar',
            'thinglink',
            'timetoast-embedder',
            'tweetable-text',
            'twitter-shortcode',
            'twitter-tools',
            'twitter-widget-pro',
            'VisualLinks.php',
            'vk-core',
            'voicethread-auto-embed',
            'widget-shortcode',
            'wordpress-importer',
            'wordpress-mu-sitewide-tags',
            'wordpress-mu-theme-stats',
            'wordpress-posts-timeline',
            'wordpress-video-plugin',
            'wpcat2tag-importer',
            'wp-chinese-conversion',
            'wp-custom-fields-search',
            'wp-display-header',
            'wp-gallery-custom-links',
            'wp-google-fonts',
            'wp-issuu',
            'wp-jquery-timelinr',
            'wp-markdown',
            'wp-mass-mailer',
            'wpml-cms-nav',
            'wpml-media',
            'wpml-sticky-links',
            'wpml-string-translation',
            'wpml-theme-tester',
            'wpml-translation-management',
            'wpmu-plugin-stats',
            'wp-nivo-slider',
            'wp-postratings',
            'wp-postviews',
            'wp-pro-quiz',
            'wp-rss-images',
            'wp-snowfall',
            'wp-thread-comment',
            'wptouch',
            'wysija-newsletter-latest-link',
            'wysija-newsletters',
            'zotpress',
        ];

        return $this->render('plugins.html.twig', [
            'title' => "WordPress Plugins",
            'plugins' => $plugins,
        ]);
    }

    /**
     * @Route("/plugins/{pluginName}", name="show_plugin")
     */
    public function showPlugin($pluginName)
    {
        return $this->render('plugin.html.twig', [
            'title' => "WordPress Plugins: " . $pluginName,
            'name' => $pluginName,
        ]);
    }
}
